personalhelper/notes/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('note/', views.NoteListView.as_view(), name='note'),
    path('note/<int:pk>/', views.NoteDetailView.as_view(),
         name='note-detail'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('tags/<int:pk>/', views.notes_by_tags, name='tag-detail'),
]

urlpatterns += [
    path('note/create/', views.NoteCreateView.as_view(), name='note-create'),
    path('note/update/<int:pk>/', views.NoteUpdate.as_view(),
         name='note-update'),
    path('note/<int:pk>/delete/', views.NoteDelete.as_view(),
         name='note-delete'),
    path('notes/create_tag/', views.TagCreate.as_view(), name='tag-create'),
]

personalhelper/personalhelper/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    path('', RedirectView.as_view(url='/contacts/', permanent=True)),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users_files/', include('users_files.urls')),
    # path('files/', include('contacts.urls')),
    path('notes/', include(('notes.urls', 'notes'),  namespace='notes')),
    path('scraper/', include(('scraper.urls', 'scraper'), namespace='scraper')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalhelper/notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    title = models.CharField(max_length=20)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this Tag."""
        return reverse('notes:tag-detail', args=[str(self.id)])


class Note(models.Model):
    title = models.CharField(max_length=20)
    tags = models.ManyToManyField(Tag)
    value = models.TextField(max_length=1000, default='LaLaLa')
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this Note."""
        return reverse('notes:note-detail', args=[str(self.id)])

    def get_short_value(self):
        result = self.value
        if len(self.value) > 50:
            result = result[:50]
        return result

personalhelper/notes/forms.py
from django import forms
from .models import Note, Tag


class NoteCreateForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'value', 'tags', 'owner']

        widgets = {
            'title': forms.TextInput(attrs={"class": "form-control"}),
            'value': forms.Textarea(attrs={"class": "form-control"}),
            'tags': forms.SelectMultiple(attrs={"class": "form-control"}),
            'owner': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner')
        super(NoteCreateForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        if Note.objects.filter(owner=self.owner, title=title).exists():
            raise forms.ValidationError(
                "You have already written a note with same title.")
        return title


class NoteUpdateForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'value', 'tags']


class AddTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data['title']
        if Tag.objects.filter(title=title).exists():
            raise forms.ValidationError(
                "You have already written a tag with same title.")
        return title

personalhelper/notes/views.py
from .forms import NoteCreateForm, NoteUpdateForm, AddTagForm
from django.conf import settings
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Tag, Note
from django.views import generic
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin


class NoteListView(LoginRequiredMixin, generic.ListView):
    model = Note
    paginate_by = 5

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    model = Note

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 10

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


@login_required(login_url='login')
def index(request):
    # """View function for home page for notes."""
    # notes = Note.objects.all()
    # notes_count = Note.objects.filter(owner = request.user).count()

    # context = {'notes': notes, 'notes_count': notes_count}

    # return render(request, 'index.html', context=context)
    return NoteListView.as_view()(request)


@login_required(login_url='login')
def notes_by_tags(request, pk):
    tag = Tag.objects.get(pk=pk)
    notes_list = Note.objects.filter(owner=request.user.id).filter(tags=tag)

    paginator = Paginator(notes_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'notes/note_list.html', {'page_obj': page_obj, 'filtered': True, 'tag': tag})


class NoteCreateView(LoginRequiredMixin, CreateView):
    form_class = NoteCreateForm
    template_name = 'notes/note_form.html'

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.owner = self.request.user
    #     self.object.save()
    #     print(form.cleaned_data['tags'])
    #     # self.object.tags.set = form.cleaned_data['tags']
    #     # self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

    def get_initial(self, *args, **kwargs):
        initial = super(NoteCreateView, self).get_initial(**kwargs)
        initial['title'] = 'My Title'
        initial['owner'] = self.request.user
        return initial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(NoteCreateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['owner'] = self.request.user
        return kwargs

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class NoteUpdate(LoginRequiredMixin, UpdateView):
    model = Note
    form_class = NoteUpdateForm
    template_name = 'notes/note_form.html'

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class NoteDelete(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('notes:note')

    def get_login_url(self) -> str:
        return settings.LOGIN_REDIRECT_URL


class TagCreate(LoginRequiredMixin, CreateView):
    model = Tag
    form_class = AddTagForm
    template_name = 'notes/tag_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('notes:note-create'))

personalhelper/notes/templates/notes/note_confirm_delete.html
{% extends 'contacts/layout.html' %}
{% block title %}Note{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Your notes, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}

{% block content %}
<div class="features">
  <h1>Delete Note</h1>
    <p>Are you sure you want to delete the note: {{ note.title }}?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete.">
    </form>
</div>
{% endblock %}

personalhelper/notes/templates/notes/note_detail.html
{% extends 'contacts/layout.html' %}

{% block title %}Notes details{% endblock %}
{% block header %}
<h1 style='margin-right: 100px'>Your notes, {{user.username|default:'Guest'}}</h1>
<li style='margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style='margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}

{% block content %}
<div class="features">
	<div>
		<h1>Title: {{ note.title }}</h1>

		<h4>Tags:</h4>
		{% if note.tags.all %}
		<ul>
			{% for tag in note.tags.all %}
			<li>
				<a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>There are no tags in this note.</p>
		{% endif %}

		<div style="margin-left:20px;margin-top:20px">
			<h4>Note:</h4>
			{{ note.value }}
		</div>
		<div>
			<ul>
				<li style='margin-left: 20px'><a href="{% url 'notes:note-update' note.id %}">Note update</a></li>
				<li style='margin-left: 20px'><a href="{% url 'notes:note-delete' note.id %}">Note delete</a></li>
			</ul>
		</div>
	</div>
</div>
{% endblock %}

personalhelper/notes/templates/notes/note_form.html
{% extends 'contacts/layout.html' %}
{% load bootstrap5 %}
{% block title %}Note{% endblock %}


{% block header %}
<h1 style='margin-right: 100px'>Your notes, {{user.username|default:'Guest'}}</h1>
<li style='margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style='margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}


{% block content %}
<div class="form-group features">
  <form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <div>
      <a href="{% url 'notes:tag-create' %}">Create Tag</a>
    </div>
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

personalhelper/notes/templates/notes/note_list.html
{% extends 'contacts/layout.html' %}
{% block title %}Note list{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Your notes, {{user.username|default:'Guest'}}</h1>
<li style='margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style='margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style='margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}

{% block content %}
<div class="features">
  {% if filtered %}
  <h2>
    All notes with tag <strong>"{{tag}}"</strong>
  </h2>
  {% endif %}
  <p>
    {% if page_obj %}
  <table class="table">
    <tr>
      <th>Title</th>
      <th>Tags</th>
      <th>Notes</th>
      <th>Action</th>
    </tr>
    {% for note in page_obj %}
    <tr class="align-middle">
      <td>
        <h3>
          {{ note.title }}
        </h3>
      </td>
      <td>{% for tag in note.tags.all %}
        <a class="link" href="{{ tag.get_absolute_url }}">{{ tag }}</a>
        {% endfor %}
      </td>
      <td>
        {{ note.get_short_value}}
      </td>
      <td>
        <a class='btn btn-info btn-sm' href="{{ note.get_absolute_url }}">Show</a>
        <a class='btn btn-info btn-sm' href="{{ note.get_absolute_url }}delete">Delete</a>
      </td>
    </tr>

    {% endfor %}
  </table>
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
  {% else %}
  <p>There are no notes in the profile.</p>
  {% endif %}
  </p>
  {% if filtered %}
  <div>
    <a class='btn btn-warning' type='submit' href="{% url 'notes:note' %}" target="_self">Clear filter</a>
  </div>
  {% endif %}
  <div>
    <a class='btn btn-warning' type='submit' href="{% url 'notes:note-create' %}" target="_self">Create Note</a>
  </div>

</div>
{% endblock %}

personalhelper/notes/templates/notes/tag_detail.html
{% extends 'contacts/layout.html' %}
{% block title %}Tag detail{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Your tag, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}


{% block content %}
<div class="features">
	<p>
		<h1>Title: {{ tag.title }}</h1>

		<div style="margin-left:20px;margin-top:20px">
			<h4>Notes:</h4>
			{% if tag.note_set.all %}
			<ul>
				{% for note in tag.note_set.all %}
				{% if note.owner == request.user %}
				<li>
					<a href="{{ note.get_absolute_url }}">{{ note.title }}</a>
				</li>
				{% endif %}
				{% endfor %}
			</ul>
			{% else %}
			<p>There are no notes with this tag.</p>
			{% endif %}
		</div>
	</p>
</div>
{% endblock %}

personalhelper/notes/templates/notes/tag_form.html
{% extends "contacts/layout.html" %}
{% block title %}Note{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Your notes, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}
{% block content %}
<div class="features">
  <p>
    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
    </form>
  </p>
</div>
{% endblock %}

personalhelper/notes/templates/notes/tag_list.html
{% extends 'contacts/layout.html' %}
{% block title %}Tag list{% endblock %}


{% block header %}
<h1 style='margin-right: 100px'>Your tags, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'notes:index' %}">Home</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note' %}">My Notes</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:tags' %}">Tags</a></li>
<li style = 'margin: 10px'><a href="{% url 'notes:note-create' %}">Create Note</a></li>
{% endblock %}


{% block content %}
<div class="features">
  <p>
      {% if tag_list %}
    <ul>
      {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no tags in the profile.</p>
    {% endif %}
  </p>
</div>
{% endblock %}