personalhelper/contacts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.index, name='index'),
    url('add_contact/', views.add_contact, name='add-contact'),
    path('show_contacts/', views.show_all, name='show-contacts'),
    path('show_contacts/<int:pk>/',
         views.ContactDetailView.as_view(), name='contact-detail'),

    path('show_contacts/<int:pk>/update',
         views.ContactUpdateView.as_view(), name='contact-update'),
    path('show_contacts/<int:pk>/delete',
         views.delete_record, name='contact-delete'),
    path('show_contacts/<int:pk>/delete_phone',
         views.delete_phone, name='delete-phone'),
    path('show_contacts/add_phone/<int:id>',
         views.add_phone, name='add_phone'),
    path('search_contact/', views.search, name='search-contact'),
    path('search_contact/<int:pk>', views.search),
    path('show_contacts/<int:id>/daystobth',
         views.days_to_birthday, name='bithday'),
    path('show_contacts/days_to/',
         views.filtered_by_day, name='by-day-to-birthday'),

    #path('<str:filepath>/', views.download_file),
]

personalhelper/notes/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('note/', views.NoteListView.as_view(), name='note'),
    path('note/<int:pk>/', views.NoteDetailView.as_view(),
         name='note-detail'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('tags/<int:pk>/', views.notes_by_tags, name='tag-detail'),
]

urlpatterns += [
    path('note/create/', views.NoteCreateView.as_view(), name='note-create'),
    path('note/update/<int:pk>/', views.NoteUpdate.as_view(),
         name='note-update'),
    path('note/<int:pk>/delete/', views.NoteDelete.as_view(),
         name='note-delete'),
    path('notes/create_tag/', views.TagCreate.as_view(), name='tag-create'),
]

personalhelper/personalhelper/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    path('', RedirectView.as_view(url='/contacts/', permanent=True)),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users_files/', include('users_files.urls')),
    # path('files/', include('contacts.urls')),
    path('notes/', include(('notes.urls', 'notes'),  namespace='notes')),
    path('scraper/', include(('scraper.urls', 'scraper'), namespace='scraper')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalhelper/contacts/models.py
from datetime import datetime, date, timedelta
from django.core import validators
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.db.models.deletion import CASCADE
from storages.backends.sftpstorage import SFTPStorage
from django.contrib.auth.models import User
SFS = SFTPStorage()


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE, null=True)
    contact_name = models.CharField(max_length=50, null=False)
    contact_photo = models.FileField(storage=SFS, null=True, blank=True)
    contact_email = models.EmailField(null=False, blank=True)
    contact_adress = models.CharField(max_length=50, null=True, blank=True)
    contact_birthday = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return f'/contacts/show_contacts/{self.pk}'

    def day_to_birhday(self, days):
        if self.contact_birthday:
            birthday = date(
                datetime.now().year, self.contact_birthday.month, self.contact_birthday.day)
            if datetime.now().date() <= birthday <= (datetime.now() + timedelta(days)).date():
                return True
        return False

    def __str__(self):
        return f'{self.contact_name}'


class Phone(models.Model):
    phone = models.CharField(max_length=10, validators=[validators.RegexValidator(
        regex='\d{10}$', message='Phone number must have 10 digits')])
    contact = models.ForeignKey(
        'Contact', on_delete=models.CASCADE)

    def __str__(self):
        return self.phone

personalhelper/contacts/forms.py
from django.db.models.fields import BLANK_CHOICE_DASH
from django.forms.fields import NullBooleanField
from .models import Contact, Phone
from django.forms import ModelForm, widgets
from django import forms


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        contact_birthday = forms.DateField(
            required=False, input_formats=['%Y-%m-%d', '%d.%m.%Y', '%d/%m/%Y'])
        fields = ['user', 'contact_name', 'contact_email',
                  'contact_birthday', 'contact_adress']
        widgets = {'user': forms.HiddenInput()}


class PhoneForm(ModelForm):
    class Meta:
        model = Phone

        fields = ['phone']


class SearchByName(forms.Form):
    contact_name = forms.CharField(max_length=10)


class SearchByDay(forms.Form):
    day_to_birthday = forms.IntegerField(max_value=360)

personalhelper/contacts/views.py
from django import template
from django.conf.urls import url
from django.core.paginator import Paginator
from django.db.models import fields
from django.shortcuts import redirect, render
from django.http import HttpResponse
import mimetypes
from django.template import loader
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView
from django.contrib.auth.decorators import login_required
import re
from datetime import date, datetime

from .forms import ContactForm, PhoneForm, SearchByDay, SearchByName
from .models import Contact, Phone


def download_file(request):

    f_path = '/file'
    filename = 'file.ext'

    f = open(f_path, 'r')
    mime_type, _ = mimetypes.guess_type(f_path)
    response = HttpResponse(f, content_type=mime_type)
    response['Content-Disposition'] = f"attachment; filename={filename}"
    return response


def phone_chek(new_value):
    if not re.match('\d{10}$', new_value):
        raise ValueError('Phone number must have 10 digits')
    else:
        new_value = new_value


@login_required(login_url='login')
def index(request):
    contact_list = Contact.objects.filter(
        user_id=request.user.id)

    paginator = Paginator(contact_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'contacts/index.html', {'record_list': page_obj})


@login_required(login_url='login')
def add_contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        form1 = PhoneForm(request.POST)
        if form.is_valid() and form1.is_valid():
            user = form.cleaned_data.get('user')
            name = form.cleaned_data.get('contact_name')
            email = form.cleaned_data.get('contact_email')
            adress = form.cleaned_data.get('contact_adress')
            birthday = form.cleaned_data.get('contact_birthday')

            phone = form1.cleaned_data.get('phone')
            phone_chek(phone)
            form = Contact(user=user, contact_name=name, contact_email=email,
                           contact_adress=adress, contact_birthday=birthday)
            form.save()
            form = Phone(phone=phone, contact=form)
            form.save()
            return redirect('/contacts/')
        else:
            return render(request, 'contacts/add_contact.html', {'form': form, 'form1': form1})
    else:
        form = ContactForm(initial={'user': request.user})
        form1 = PhoneForm()
        return render(request, 'contacts/add_contact.html', {'form': form, 'form1': form1})


@login_required(login_url='login')
def show_all(request):
    contact_list = Contact.objects.filter(
        user_id=request.user.id)
    template = loader.get_template('contacts/show_all.html')
    context = {
        'record_list': contact_list
    }
    print(context)
    return render(request, 'contacts/show_all.html', {'record_list': contact_list})


class ContactDetailView(DetailView):
    model = Contact
    template_name = 'contacts/detail_view.html'
    context_object_name = 'contact'


class ContactUpdateView(UpdateView):
    model = Contact
    template_name = 'contacts/update_contact.html'

    fields = ['contact_email', 'contact_birthday', 'contact_adress']


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = 'contacts/'
    template_name = 'contacts/delete_view.html'


@login_required(login_url='login')
def delete_record(request, pk):
    contact = Contact.objects.get(pk=pk)
    contact.delete()
    return index(request)


@login_required(login_url='login')
def delete_phone(request, pk):
    phone = Phone.objects.get(pk=pk)
    phone.delete()
    return index(request)


@login_required(login_url='login')
def search(request):

    if request.method == 'POST':
        contact_list = Contact.objects.filter(user=request.user.id)
        print(Contact._meta.fields)
        # print(contact_list)
        form = SearchByName(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('contact_name')

            # print(name)
            try:
                contacts = contact_list.filter(contact_name__icontains=name)
                return render(request, 'contacts/index.html', {'record_list': contacts, 'mode': 'search'})
            except:
                error = 'No contacts with such name. Search is case sensitive'
                form = SearchByName()
                return render(request, 'contacts/index.html', {'form': form, 'error': error})
        else:
            error = 'No contats with sush name. Search is case sensitive'
            form = SearchByName()
            return render(request, 'contacts/search_contact.html', {'form': form, 'error': error})

    else:
        form = SearchByName()
        form1 = SearchByDay()
        return render(request, 'contacts/search_contact.html', {'form': form, 'form1': form1})


@login_required(login_url='login')
def add_phone(request, id):
    form = PhoneForm()
    # print(id)
    person = Contact.objects.get(id=id)
    if request.method == "POST":
        forma = PhoneForm(request.POST)
        if forma.is_valid():
            phone = forma.cleaned_data.get('phone')
            phone1 = Phone(phone=phone, contact=person)
            phone1.save()
            return HttpResponseRedirect("/")
        else:
            error = 'Enter the valid phone. Phone number must have 10 digits'
            form = PhoneForm()
            return render(request, 'contacts/add_phone.html', {'form': forma, 'error': error, 'person': person})
    else:
        return render(request, 'contacts/add_phone.html', {'form': form, 'person': person})


def count_days(d_now, d_birth):
    if d_now > d_birth:
        d_birth = date(d_birth.year + 1, d_birth.month, d_birth.day)
    return (d_birth - d_now).days


@login_required
def days_to_birthday(request, id):

    birthday = Contact.objects.get(id=id)

    if birthday.contact_birthday != None:

        result = count_days(datetime.now().date(), date(year=datetime.now().year, month=int(
            birthday.contact_birthday.month), day=int(birthday.contact_birthday.day)))

        template = loader.get_template('contacts/bithday.html')
        context = {
            'record': birthday,
            'birthday': result
        }
        return HttpResponse(template.render(context, request))
    else:
        error = "This contact has not date of birthday"
        template = loader.get_template('contacts/bithday.html')
        context = {
            'error': error,
        }
        return HttpResponse(template.render(context, request))


@login_required(login_url='login')
def filtered_by_day(request):
    if request.method == 'POST':
        form = SearchByDay(request.POST)
        if form.is_valid():
            day_to_birtday = form.cleaned_data.get('day_to_birthday')
            contact_list = Contact.objects.filter(user=request.user.id)
            contacts = []
            for contact in contact_list:
                if contact.day_to_birhday(day_to_birtday):
                    contacts.append(contact)
    return render(request, 'contacts/index.html', {'record_list': contacts, 'mode': 'search'})

personalhelper/contacts/templates/contacts/add_contact.html
{% extends 'contacts/layout.html' %}
{% block title %}Add contact{% endblock %}
{% block header %}
<h1 style='margin-right: 100px'>Hello, {{ user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <h1>Add contact</h1>
    <p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {{form1.as_p}}
            <input type='submit' value='Submit'>
        </form>
    </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/add_phone.html
{% extends 'contacts/layout.html' %}

{% block title %}Add phone{% endblock %}

{% block header %}
<h1>Hello, {{user.username|default:'Guest'}}</h1>
{% endblock %}

{% block content %}
<div class="features">
    <p>
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Add phone to contact {{ person.contact_name }}</h1>
        {{ form.as_p }}
        <input type='submit' value='Submit'>
        </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/bithday.html
{% extends 'contacts/layout.html' %}
{% block title %} Birthday {% endblock %}
{% block header %}
<h1 style='margin-right: 100px'>Contacs birthday, {{ user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
        <h1>{{record.contact_name }}</h1>
        <p>Email - {{record.contact_email}}</p>
        <p>Adress - {{record.contact_adress}}</p>
        <p>Birthday - {{record.contact_birthday}}</p>
        <p>Left days to Birthday - {{birthday}}</p>
        {{error}}
    </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/create.html
{% extends 'contacts/layout.html' %}

{% block title %}Create{% endblock %}

{% block header %}
<h1>Create, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
        <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        </form>
    </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/delete_view.html
{% extends 'contacts/layout.html' %}

{% block title %}Delete contact{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Delete contact, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
        <form action="" method="POST">
            {% csrf_token %}
            <br>
            <br>
            <button type='submit'>Delete contact</button>
        </form>
    </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/detail_view.html
{% extends 'contacts/layout.html' %}

{% block title %}Detail contact{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Your detail contact, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
  <h1>{{contact.contact_name }}</h1>

  {% for phone in contact.phone_set.all %}
  {{ phone }} <br>
  {% endfor %}
  <p>Email - {{contact.contact_email}}</p>
  <p>Adress - {{contact.contact_adress}}</p>
  <p>Birthday - {{contact.contact_birthday}}</p>
  <table class="btn">
    <tr>
      <td><a class='btn btn-warning' href="/contacts/show_contacts/{{contact.id}}/delete">Delete contact</a></td>
      <td><a class='btn btn-warning' href="/contacts/show_contacts/{{contact.id}}/update">Update contact</a></td>
    </tr>
    <tr>
      <td><a class='btn btn-warning' href="/contacts/show_contacts/add_phone/{{contact.id}}">ADD phone</a></td>
      <td><a class='btn btn-warning' href="/contacts/show_contacts/{{contact.id}}/daystobth">Day to birthday</a></td>
    </tr>
  </table>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/index.html
{% extends 'contacts/layout.html' %}
{% load static %}
{% block title %}Contacts{% endblock %}

{% block header %}
<h1>Hello, {{ user.username|default:'Guest'}}</h1>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% include "contacts/show_all.html" %}
{% else %}
<a href="{% url 'login' %}"><img src="{% static 'contacts/img/logo.jpg' %}" alt="Лого"></a>
{% endif %}
{% endblock %}

personalhelper/contacts/templates/contacts/layout.html
{% load static %}
<!doctype html>
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<meta name="viewport"
		content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'contacts/css/main.css' %}">
</head>

<body>
	<aside>
		<img src="{% static 'contacts/img/logo.jpg' %}" alt="Лого">
		<span class="logo">Personal</span>
		<span class="logo">Assistant</span>
		<h3>Navigation</h3>
		{% if user.is_authenticated %}
		<ul>
			<li><a href="{% url 'contacts:index' %}">Contacts</a></li>
			<li><a href="{% url 'notes:index' %}">Notes</a></li>
			<li><a href="{% url 'userfiles' %}">User files</a></li>
			<li><a href="{% url 'scraper:index' %}">Sports news</a></li>
			<li><a href="{% url 'logout' %}">Logout</a></li>
			<li><a href="{% url 'password_change' %}">Change password</a></li>
		</ul>
		{% else %}
		<a href="{% url 'users:login' %}">Login</a>
		{% endif %}
	</aside>
	<main>
		<header class="page-header">
			{% block header %}

			{% endblock %}
		</header>
		<section class="page-content">
			{% block content %}
			{% endblock %}
		</section>
	</main>
	{% block footer %}
	{% endblock %}
</body>

</html>

personalhelper/contacts/templates/contacts/search_contact.html
{% extends 'contacts/layout.html' %}

{% block title %}Search contact{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Search contact, {{user.username|default:'Guest'}}</h1>
<li style='margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style='margin: 10px'><a href="{% url 'contacts:index' %}">Show contacts</a></li>
<li style='margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
    <form action="{% url 'contacts:search-contact' %}" method="POST">
        {% csrf_token %}
        <h5>{{message}}</h5>
        {{ form.as_p }}
        {{error}}
        <input type='submit' value='Search'><br>
    </form>
    </p>
    <p>
    <form action="{% url 'contacts:by-day-to-birthday' %}" method="POST">
        {% csrf_token %}
        <h5>{{message}}</h5>
        {{ form1.as_p }}
        {{error}}
        <input type='submit' value='Search'><br>
    </form>
    </p>
</div>
{% endblock %}

personalhelper/contacts/templates/contacts/show_all.html
{% block content %}
<div class="features">
    {% if mode %}
    <h2>Found contacts in your Adressbook</h2>
    {% else %}
    <h2>All contacts in your Adressbook</h2>
    {% endif %}

    {{mode}}

    {% if record_list %}
    <table class='table'>
        <tr>
            <th>Name</th>
            <th>Mail</th>
            <th>Birthday</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Action</th>
        </tr>
        {% for record in record_list %}
        <tr class="align-middle">
            <td>{{ record.contact_name }}</td>
            <td>{% if record.contact_email %} {{record.contact_email}} {% else %}
                ----
                {% endif %}
            </td>
            <td>{% if record.contact_birthday %} {{record.contact_birthday}} {% else %}
                ----
                {% endif %}
            </td>
            <td>{% if record.contact_address %} {{record.contact_address}} {% else %}
                ----
                {% endif %}
            </td>
            <td>
                {% for phone in record.phone_set.all %}
                {{ phone }} <a class="link" href="/contacts/show_contacts/{{phone.id}}/delete_phone">Del</a>
                <br>
                {% endfor %}
            </td>
            <td>
                <a class='btn btn-info btn-sm' href="/contacts/show_contacts/add_phone/{{record.id}}">Add phone</a>
                <!-- <a class="btn btn-info" href="/contacts/show_contacts/{{record.id}}">Show detail</a> -->
                <a class="btn btn-info btn-sm" href="/contacts/show_contacts/{{record.id}}/delete">Delete</a>
                <a class="btn btn-info btn-sm" href="/contacts/show_contacts/{{record.id}}/update">Edit</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <span class="step-links">
        {% if record_list.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ record_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ record_list.number }} of {{ record_list.paginator.num_pages }}.
        </span>

        {% if record_list.has_next %}
        <a href="?page={{ record_list.next_page_number }}">next</a>
        <a href="?page={{ record_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    {% else %}
    <p>No contacts are available.</p>
    {% endif %}
    <p>
        {% if mode %}
        <a class='btn btn-warning' type="submit" href="{% url 'contacts:index' %}" target='_self'>Show all
            contacts</a>
        {% endif %}
        <a class='btn btn-warning' type="submit" href="{% url 'contacts:add-contact' %}" target='_self'>Add contact</a>
        <a class='btn btn-warning' type="submit" href="{% url 'contacts:search-contact' %}" target='_self'>Search</a>
    </p>
</div>

{% endblock content%}

personalhelper/contacts/templates/contacts/show_contact.html
{% extends 'contacts/layout.html' %}

{% block title %}Show contact{% endblock %}

{% block header %}
<h1>Show contact, {{user.username|default:'Guest'}}</h1>
<li style='margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style='margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style='margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
    <h1>{{record_list.contact_name }}</h1>
    <p>{{record_list.contact_phone}}</p>
    <p>Email - {{record_list.contact_email}}</p>
    <p>Adress - {{record_list.contact_adress}}</p>
    <p>Birthday - {{record_list.contact_birthday}}</p>
    </p>

</div>
{% endblock content %}

personalhelper/contacts/templates/contacts/update_contact.html
{% extends 'contacts/layout.html' %}

{% block title %}Update contact{% endblock %}

{% block header %}
<h1 style='margin-right: 100px'>Update contact, {{user.username|default:'Guest'}}</h1>
<li style = 'margin: 10px'><a href="{% url 'contacts:add-contact' %}">Add contact</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:show-contacts' %}">Show contacts</a></li>
<li style = 'margin: 10px'><a href="{% url 'contacts:search-contact' %}">Search contacts</a></li>
{% endblock %}

{% block content %}
<div class="features">
    <p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Submit'>
        </form>
    </p>
</div>
{% endblock %}